[package]
name = "insurance"
version = "0.1.0"
edition = "2023_11"

[lib]

[dependencies]
starknet.workspace = true
snforge_std.workspace = true
openzeppelin.workspace = true
components.workspace = true


[[target.starknet-contract]]